/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_JNIUsage */

#ifndef _Included_com_example_test_JNIUsage
#define _Included_com_example_test_JNIUsage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_JNIUsage
 * Method:    printMsg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_test_JNIUsage_printMsg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
